### ISSUE TITLE
repo lacks top level LICENSE file.  Suggest MIT license

### ISSUE THREAD

**Issue by MarkAtwood** [colcon/colcon-metadata-repository#3]
This repo lacks a top level LICENSE file.
The MIT license makes the most sense for this repo.

**Comment by dirk-thomas** [comment]
The repository only contains configuration options. Can you argue why you think the MIT license would be a good fit for this kind of information?

**Comment by MarkAtwood** [comment]
Either the MIT license or the CC0 license would work here.
Repos that don't have LICENSE files are difficult for corporations to work with.
